BahokBdDelivery/Models/MarchentProfileDetail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BahokBdDelivery.Models
{
    public partial class MarchentProfileDetail
    {
        public MarchentProfileDetail()
        {
            MarchentCharge = new HashSet<MarchentCharge>();
            MarchentPaymentDetails = new HashSet<MarchentPaymentDetails>();
            MarchentStore = new HashSet<MarchentStore>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Image { get; set; }
        public string Logo { get; set; }
        public string Phone { get; set; }
        public bool Status { get; set; }
        public string BusinessName { get; set; }
        public string BusinessLink { get; set; }
        public string BusinessAddress { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public string RoutingName { get; set; }
        public string BranchName { get; set; }
        public string LastIpAddress { get; set; }
        public DateTime CreateDateTime { get; set; }
        public Guid? PaymentTypeId { get; set; }
        public Guid? PaymentBankingId { get; set; }
        public virtual ICollection<MarchentCharge> MarchentCharge { get; set; }
        public virtual ICollection<MarchentPaymentDetails> MarchentPaymentDetails { get; set; }
        public virtual ICollection<MarchentStore> MarchentStore { get; set; }
    }
}

BahokBdDelivery/Models/MarchentProfileDetails.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BahokBdDelivery.Models
{
    public partial class MarchentProfileDetails
    {
        public MarchentProfileDetails()
        {
            PickupLocations = new HashSet<PickupLocations>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Image { get; set; }
        public string Logo { get; set; }
        public string Phone { get; set; }
        public string BusinessName { get; set; }
        public string BusinessLink { get; set; }
        public string BusinessAddress { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public string RoutingName { get; set; }
        public string BranchName { get; set; }
        public int? ProfileStatus { get; set; }
        public string LastIpAddress { get; set; }
        public DateTime? DateTime { get; set; }
        public Guid? PaymentTypeId { get; set; }
        public Guid? PaymentBankingId { get; set; }

        public virtual ICollection<PickupLocations> PickupLocations { get; set; }
    }
}

BahokBdDelivery/Areas/SuperAdmin/Controllers/MarchentProfileDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BahokBdDelivery.Data;
using BahokBdDelivery.Models;
using Microsoft.AspNetCore.Hosting;
using BahokBdDelivery.ViewModels;
using System.IO;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.WebUtilities;
using System.Text;
using System.Text.Encodings.Web;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Identity.UI.Services;
using static BahokBdDelivery.Helper;

namespace BahokBdDelivery.Areas.SuperAdmin.Controllers
{
    [Area("SuperAdmin")]
    public class MarchentProfileDetailsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<MarchentProfileDetailsController> _logger;
        private readonly IEmailSender _emailSender;
        private readonly RoleManager<IdentityRole> _roleManager;
        public MarchentProfileDetailsController(ILogger<MarchentProfileDetailsController> logger, IEmailSender emailSender, RoleManager<IdentityRole> roleManager, ApplicationDbContext context, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _signInManager = signInManager;
            _userManager = userManager;
            _roleManager = roleManager;
            _emailSender = emailSender;
            _logger = logger;
        }

        // GET: SuperAdmin/MarchentProfileDetail
        public async Task<IActionResult> Index()
        {
            string msg = Convert.ToString(TempData["msg"]);
            ViewBag.approve = msg;
            return View(await _context.MarchentProfileDetail.ToListAsync());
        }
  
        public async Task< IActionResult> Approve(Guid?id)
        {
            var marchent = _context.MarchentProfileDetail.FirstOrDefault(c => c.Id == id);
            var user = new ApplicationUser { UserName = marchent.Phone, Email = marchent.Email};
            try
            {
                var result = await _userManager.CreateAsync(user, marchent.Password);
                var uName = await _userManager.FindByNameAsync(marchent.Phone);
                if (result.Succeeded)
                {
                    // _logger.LogInformation("User created a new account with password.");

                    var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                    code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
                    var callbackUrl = Url.Page(
                        "/Account/ConfirmEmail",
                        pageHandler: null,
                        values: new { area = "Identity", userId = user.Id, code = code },
                        protocol: Request.Scheme);

                    await _emailSender.SendEmailAsync(marchent.Email, "Confirm your email",
                        $"Please confirm your account by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.");

                    if (_userManager.Options.SignIn.RequireConfirmedAccount)
                    {
                        code = Encoding.UTF8.GetString(WebEncoders.Base64UrlDecode(code));
                        var result1 = await _userManager.ConfirmEmailAsync(user, code);
                    }
                    if (uName != null)
                    {
                        var roleName = "Marchent";
                        var mRole = await _roleManager.FindByNameAsync(roleName);
                        if (mRole != null)
                        {
                            await _userManager.AddToRoleAsync(uName, mRole.Name);
                        }
                        marchent.Status = true;
                        await _context.SaveChangesAsync();
                    }
                    //else
                    //{
                    //    await _signInManager.SignInAsync(user, isPersistent: false);
                    //    return LocalRedirect(returnUrl);
                    //}
                }

            }
            catch(Exception ex)
            {

            }
     

            return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAllMarchent", _context.MarchentProfileDetail.ToList()) });
        }
        
        //// GET: SuperAdmin/MarchentProfileDetail/Create
        [NoDirectAccess]
        public IActionResult Create()
        {
           // ViewData["TypeId"] = new SelectList(_context.PaymentBankingType, "Id", "BankingMethodName");
            return View(new MarchentProfileDetailVm());
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MarchentProfileDetailVm vm)
        {
            if (ModelState.IsValid)
            {

                MarchentProfileDetail entity = new MarchentProfileDetail();
                var samePhone = _context.MarchentProfileDetail.Where(c => c.Phone == vm.Phone);
                var count = samePhone.Count();
                if (count > 0)
                {
                    ViewBag.error = "The phone number already exist";
                    return View(vm);
                }
                entity.Name = vm.Name;
                entity.Email = vm.Email;
                entity.Phone = vm.Phone;
                entity.BusinessName = vm.BusinessName;
                entity.BusinessLink = vm.BusinessLink;
                entity.BusinessAddress = vm.BusinessAddress;
                entity.AccountName = vm.AccountName;
                entity.AccountNumber = vm.AccountNumber;

                entity.LastIpAddress = vm.LastIpAddress;
                entity.CreateDateTime = DateTime.Now;
                entity.Password = "112345";
                string uniqueFileNameForImage = null;
                string uniqueFileNameForLogo = null;
                if (vm.Image != null)
                {

                    string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                    uniqueFileNameForImage = Guid.NewGuid().ToString() + "_" + vm.Image.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileNameForImage);
                    await vm.Image.CopyToAsync(new FileStream(filePath, FileMode.Create));
                    entity.Image = "images/" + uniqueFileNameForImage;
                }
                if (vm.Logo != null)
                {

                    string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "logos");
                    uniqueFileNameForLogo = Guid.NewGuid().ToString() + "_" + vm.Logo.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileNameForLogo);
                    await vm.Logo.CopyToAsync(new FileStream(filePath, FileMode.Create));
                    entity.Logo = "logos/" + uniqueFileNameForLogo;
                }
                entity.Id = Guid.NewGuid();
                _context.MarchentProfileDetail.Add(entity);
                await _context.SaveChangesAsync();
                var paymentDetail = new MarchentPaymentDetails();
                paymentDetail.MarchentId = entity.Id;
                paymentDetail.PaymentNameId = vm.PaymentBankingId;
                paymentDetail.PaymentTypeId = vm.PaymentTypeId;
                paymentDetail.BranchName = vm.BranchName;
                paymentDetail.RoutingName = vm.RoutingName;
                _context.MarchentPaymentDetails.Add(paymentDetail);
                await _context.SaveChangesAsync();
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAllMarchent", _context.MarchentProfileDetail.ToList()) });

                
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Create", vm) });
        }

        [NoDirectAccess]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            MarchentProfileDetailVm vm = new MarchentProfileDetailVm();
            var entity = await _context.MarchentProfileDetail.FindAsync(id);
            if (vm == null)
            {
                return NotFound();
            }
            vm.Name = entity.Name;
            vm.Email = entity.Email;
            vm.Phone = entity.Phone;
            vm.BusinessName = entity.BusinessName;
            vm.BusinessLink = entity.BusinessLink;
            vm.BusinessAddress = entity.BusinessAddress;
            vm.AccountName = entity.AccountName;
            vm.AccountNumber = entity.AccountNumber;
            vm.LastIpAddress = entity.LastIpAddress;
            vm.DateTime = entity.CreateDateTime;
            vm.DisplayImage = entity.Image;
            vm.DisplayLogo = entity.Logo;
            vm.Status = entity.Status;
            var marchant = _context.MarchentPaymentDetails.FirstOrDefault(c => c.MarchentId == entity.Id);
            var odlPaymentType = _context.PaymentBankingType.FirstOrDefault(c => c.Id == marchant.PaymentTypeId);
            vm.OdlPaymentTypeName = odlPaymentType.BankingMethodName;
            var odlBank = _context.PaymentBankingOrganization.FirstOrDefault(c => c.Id == marchant.PaymentNameId);
            vm.OdlBankName = odlBank.OrganizationName;
           // var odlBranch = _context.BankBranch.FirstOrDefault(c => c.Id == marchant.BranchId);
            vm.OdlBranchName = marchant.BranchName;
            vm.OdlRouting = marchant.RoutingName;
            return View(vm);
        }

BahokBdDelivery/Areas/SuperAdmin/Views/MarchentProfileDetails/Create.cshtml
@model BahokBdDelivery.ViewModels.MarchentProfileDetailVm

@{
    ViewData["Title"] = "Create";
    Layout = null;
}

<div class="row">
    <div class="col-12 col-lg-12">
        <div class="card mb-4">
            <div class="card-header ">
                <h2>Create Merchent</h2>
            </div>
            <div class="card-body">
                <form asp-action="Create"onsubmit="return jQueryAjaxPost(this);"  enctype="multipart/form-data"autocomplete="off">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="col-12 col-md-12 col-lg-12">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label asp-for="Name" class="control-label"></label>
                                        <input asp-for="Name" class="form-control" />
                                        <span asp-validation-for="Name" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-md-6 col-12 col-lg-6">
                                    <div class="form-group">
                                        <label asp-for="Email" class="control-label"></label>
                                        <input type="email" asp-for="Email" class="form-control" />
                                        <input type="hidden" asp-for="Password" id="password" />
                                        <span asp-validation-for="Email" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 col-12 col-lg-6 ">
                                    <div class="form-group">
                                        <label>Marchent Image</label>
                                        <input class=" form-control " type="file"  onchange="loadImg(event)" asp-for="Image" />
                                    </div>
                                </div>
                                <div class="col-md-6 col-12 col-lg-6 ">
                                    <div class="form-group">
                                        <label>Logo</label>
                                        <input class=" form-control " onchange="loadLogo(event)"  type="file" asp-for="Logo" />
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 col-12">
                                    <img id="img" src="#" style="height:100PX;width:100PX; border:solid 1px;" />
                                </div>
                                <div class="col-md-6 cpl-12">
                                    <img id="logo" src="#" style="height: 100PX; width: 100PX; border:solid 1px;" />
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 col-12 col-lg-6 ">
                                    <div class="form-group">
                                        <label asp-for="Phone" class="control-label"></label>
                                        <input asp-for="Phone" id="phonenumber" type="number" class="form-control" />

                                        <span asp-validation-for="Phone" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-md-6 col-12 col-lg-6 ">
                                    <div class="form-group">
                                        <label asp-for="BusinessName" class="control-label"></label>
                                        <input asp-for="BusinessName" class="form-control" />
                                        <span asp-validation-for="BusinessName" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 col-12 col-lg-6 ">
                                    <div class="form-group">
                                        <label asp-for="BusinessLink" class="control-label"></label>
                                        <input asp-for="BusinessLink" class="form-control" />
                                        <span asp-validation-for="BusinessLink" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-md-6 col-12 col-lg-6 ">
                                    <div class="form-group">
                                        <label asp-for="BusinessAddress" class="control-label"></label>
                                        <input asp-for="BusinessAddress" class="form-control" />
                                        <span asp-validation-for="BusinessAddress" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 col-12 col-lg-6 ">
                                    <div class="form-group">
                                        <label asp-for="AccountName" class="control-label"></label>
                                        <input asp-for="AccountName" class="form-control" />
                                        <span asp-validation-for="AccountName" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-md-6 col-12 col-lg-6 ">
                                    <div class="form-group">
                                        <label asp-for="AccountNumber" class="control-label"></label>
                                        <input asp-for="AccountNumber" class="form-control" />
                                        <span asp-validation-for="AccountNumber" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6 col-12 col-lg-6">
                                    <div class="form-group">
                                        <label  class="control-label">PaymentType</label>
                                        <select asp-for="PaymentTypeId" class="form-control" onclick="bankList()" id="Type"></select>
                                        <span asp-validation-for="PaymentTypeId" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-md-6 col-12 col-lg-6 ">
                                    <div class="form-group">
                                        <label asp-for="PaymentBankingId" class="control-label"></label>
                                        <select asp-for="PaymentBankingId" class="form-control" onclick="branchList()" id="Organize"></select>
                                        <span asp-validation-for="PaymentBankingId" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row" id="hideDiv">
                                <div class="col-md-12 col-12 col-lg 12">
                                    <div class="row">
                                        <div class="col-md-6 col-12 col-lg-6 ">
                                            <div class="form-group">
                                                <label asp-for="RoutingName" class="control-label"></label>
                                                <input asp-for="RoutingName" class="form-control" id="Route" />
                                                <span asp-validation-for="RoutingName" class="text-danger"></span>
                                            </div>
                                        </div>
                                        <div class="col-md-6 col-12 col-lg-6 ">
                                            <div class="form-group">
                                                <label  class="control-label">Branch</label>
                                                <input asp-for="BranchName" class="form-control" />                                              
                                                <span asp-validation-for="BranchName" class="text-danger"></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Submit" class="btn btn-primary" />   
                                <a class="btn btn-info" href="#">Send SMS</a>
                                <a class="btn btn-info" href="#">Send Mail</a>
                            </div>
                        </div>

                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

BahokBdDelivery/Areas/SuperAdmin/Views/MarchentProfileDetails/Delete.cshtml
@model BahokBdDelivery.Models.MarchentProfileDetail

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MarchentProfileDetail</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Logo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Logo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BusinessName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BusinessName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BusinessLink)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BusinessLink)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BusinessAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BusinessAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AccountName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AccountName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AccountNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AccountNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoutingName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoutingName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BranchName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BranchName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastIpAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastIpAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreateDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreateDateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentTypeId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PaymentTypeId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentBankingId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PaymentBankingId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BahokBdDelivery/Areas/SuperAdmin/Views/MarchentProfileDetails/Index.cshtml
@model IEnumerable<BahokBdDelivery.Models.MarchentProfileDetail>

@{
    //int i = 1;
    ViewData["Title"] = "Index";
}


<div class="card mb-4">
    <div class="card-header ">
        <h2>Manage Marche</h2>
        <a onclick="showInPopup('@Url.Action("Create","MarchentProfileDetails",null,Context.Request.Scheme)','Marchent Details' )" class="btn  text-black-50"><i class="fas fa-random"></i> New Marchent</a>
    </div>
    <div id="view-all" class="card-body">
        @await Html.PartialAsync("_ViewAllMarchent", Model)
    </div>
</div>

BahokBdDelivery/Areas/SuperAdmin/Views/MarchentProfileDetails/_ViewAllMarchent.cshtml
@model IEnumerable<BahokBdDelivery.Models.MarchentProfileDetail>

@if (Model != null)
{
    <table class="table table-scripted">

        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td style="width:15px"><img src="~/@item.Image" style="height:20px;width:20px; margin-top:8px;" /></td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)<br />
                        @Html.DisplayFor(modelItem => item.Phone),@Html.DisplayFor(modelItem => item.Email)<br />
                        @if (item.Status)
                        {
                            <span class="text-success">Enable</span>
                        }
                        else
                        {
                            <span class="text-warning">Disable</span>
                        }
                    </td>


                    <td style="width:200px">
                        <a onclick="showInPopup('@Url.Action("AddMarhentStore", "MarchentStores", new { id = item.Id }, Context.Request.Scheme)','Marchent Store Details' )"class="btn btn-sm btn-info text-white"> <i class="fas fa-store"></i></a>
                        <a onclick="showInPopup('@Url.Action("AddCharge", "MarchentCharge", new { id = item.Id }, Context.Request.Scheme)','Marchent Charge Details' )" class="btn btn-sm btn-info text-white"><i class="fas fa-dollar-sign"></i></a>
                        <a onclick="showInPopup('@Url.Action("Edit", "MarchentProfileDetails", new { id = item.Id }, Context.Request.Scheme)','Marchent Profile Details' )" class="btn btn-sm btn-info text-white"><i class="fas fa-random"></i></a>
                        <a onclick="Approve('@Url.Action("Approve", "MarchentProfileDetails", new { id = item.Id }, Context.Request.Scheme)','Marchent Profile Details')" class="btn btn-sm btn-info text-white"><i class="fas fa-check"></i></a>
                        <a onclick="showInPopup('@Url.Action("EditCharge", "MarchentCharge", new { id = item.Id }, Context.Request.Scheme)','UpDate Marchent Charge Details')" class="btn btn-sm btn-info text-white"><i class="fas fa-file-invoice-dollar"></i></a>
                    </td>
                </tr>

            }

        </tbody>
    </table>
}
@*@section Scripts
{
    <script>
        $(function(){
            var approve = '@ViewBag.approve';
            if (approve != null) {
                toastr.success(approve);
            }

        });
    </script>
}*@