BahokBdDelivery/Models/BankBranch.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BahokBdDelivery.Models
{
    public partial class BankBranch
    {
        public BankBranch()
        {
            MarchentPaymentDetails = new HashSet<MarchentPaymentDetails>();
        }

        public Guid Id { get; set; }
        public string BranchName { get; set; }
        public string RoutingName { get; set; }
        public Guid? BankId { get; set; }
        public bool? Status { get; set; }

        public virtual PaymentBankingOrganization Bank { get; set; }
        public virtual ICollection<MarchentPaymentDetails> MarchentPaymentDetails { get; set; }
    }
}

BahokBdDelivery/Areas/SuperAdmin/Controllers/BankBranchesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BahokBdDelivery.Data;
using BahokBdDelivery.Models;
using static BahokBdDelivery.Helper;

namespace BahokBdDelivery.Areas.SuperAdmin.Controllers
{
    [Area("SuperAdmin")]
    public class BankBranchesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BankBranchesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: SuperAdmin/BankBranches
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.BankBranch.Include(b => b.Bank);
            return View(await applicationDbContext.ToListAsync());
        }

        [NoDirectAccess]
        public async Task<IActionResult> AddOrEdit(Guid id)
        {
            if (id == Guid.Parse("00000000-0000-0000-0000-000000000000"))
            {
                ViewData["BankId"] = new SelectList(_context.PaymentBankingOrganization, "Id", "OrganizationName");
                return View(new BankBranch());
            }
                
            else
            {
                var branchModel = await _context.BankBranch.FindAsync(id);
                if (branchModel == null)
                {
                    return NotFound();
                }
                ViewData["BankId"] = new SelectList(_context.PaymentBankingOrganization, "Id", "OrganizationName", branchModel.BankId);
                return View(branchModel);
            }

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit(Guid id, BankBranch branch)
        {
            if (ModelState.IsValid)
            {
                if (id == Guid.Parse("00000000-0000-0000-0000-000000000000"))
                {
                    BankBranch entity = new BankBranch();
                    entity.Id = Guid.NewGuid();
                    entity.BranchName = branch.BranchName;
                    entity.BankId = branch.BankId;
                    _context.Add(entity);
                    await _context.SaveChangesAsync();
                }

                else
                {
                    try
                    {
                        _context.Update(branch);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!BankBranchExists(branch.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                }
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAllBranch", _context.BankBranch.Include(c=>c.Bank).ToList()) });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "AddOrEdit", branch) });

        }

        // GET: SuperAdmin/BankBranches/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bankBranch = await _context.BankBranch
                .Include(b => b.Bank)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bankBranch == null)
            {
                return NotFound();
            }

            return View(bankBranch);
        }

        // POST: SuperAdmin/BankBranches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var bankBranch = await _context.BankBranch.FindAsync(id);
            _context.BankBranch.Remove(bankBranch);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BankBranchExists(Guid id)
        {
            return _context.BankBranch.Any(e => e.Id == id);
        }
    }
}

BahokBdDelivery/Areas/SuperAdmin/Views/BankBranches/AddOrEdit.cshtml
@model BahokBdDelivery.Models.BankBranch
@{
    ViewData["Title"] = "AddOrEdit";
    Layout = null;
}

<div class="card mb-4">
    <div class="card-header">
        Create Branch
    </div>
    <div class="card-body">
        <form asp-action="AddOrEdit" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPost(this);" autocomplete="off">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="Id" />
                <label asp-for="BranchName" class="control-label"></label>
                <input asp-for="BranchName" class="form-control" />
                <span asp-validation-for="BranchName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BankId" class="control-label"></label>
                <select asp-for="BankId" class="form-control" asp-items="ViewBag.BankId"></select>
                <span asp-validation-for="BankId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

BahokBdDelivery/Areas/SuperAdmin/Views/BankBranches/Index.cshtml
@model IEnumerable<BahokBdDelivery.Models.BankBranch>

@{
    ViewData["Title"] = "Index";
    //  int i = 1;
}
<div class="card mb-4">
    <div class="card-header ">
        <h2>Manage Branch</h2>
        <a onclick="showInPopup('@Url.Action("AddOrEdit","BankBranches",null,Context.Request.Scheme)','New Branch' )" class="btn  text-black-50"><i class="fas fa-random"></i> New Branch</a>
    </div>
    <div id="view-all" class="card-body">
        @await Html.PartialAsync("_ViewAllBranch", Model)
    </div>
</div>