BahokBdDelivery/Areas/SuperAdmin/Controllers/PaymentBankingTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BahokBdDelivery.Data;
using BahokBdDelivery.Models;
using BahokBdDelivery.Views.ViewModels;
using static BahokBdDelivery.Helper;

namespace BahokBdDelivery.Areas.SuperAdmin.Controllers
{
    [Area("SuperAdmin")]
    public class PaymentBankingTypesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PaymentBankingTypesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: SuperAdmin/PaymentBankingTypes
        [HttpGet]
        [DisableRequestSizeLimit]
        public async Task<IActionResult> Index()
        {
            return View(await _context.PaymentBankingType.ToListAsync());
        }
        [HttpGet("/PaymentBankingTypes/litPayType")]
        [DisableRequestSizeLimit]
        public async Task<IActionResult> GetAllType()
        {
            return View(await _context.PaymentBankingType.ToListAsync());
        }
  
        [NoDirectAccess]
        public async Task<IActionResult> AddOrEdit(Guid id)
        {
            if (id == Guid.Parse("00000000-0000-0000-0000-000000000000"))
                return View(new PaymentBankingType());
            else
            {
                var typeModel = await _context.PaymentBankingType.FindAsync(id);
                if (typeModel == null)
                {
                    return NotFound();
                }
                return View(typeModel);
            }

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit(Guid id, PaymentBankingType paymentBankingType)
        {
            if (ModelState.IsValid)
            {
                if (id == Guid.Parse("00000000-0000-0000-0000-000000000000"))
                {
                    PaymentBankingType entity = new PaymentBankingType();
                    //entity.Id = Guid.NewGuid();
                    entity.BankingMethodName = paymentBankingType.BankingMethodName;
                    _context.Add(entity);
                    await _context.SaveChangesAsync();
                }

                else
                {
                    try
                    {
                        _context.Update(paymentBankingType);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!PaymentBankingTypeExists(paymentBankingType.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                }
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAll", _context.PaymentBankingType.ToList()) });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "AddOrEdit", paymentBankingType) });

        }

        // GET: SuperAdmin/PaymentBankingTypes/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            var paymentBankingType = await _context.PaymentBankingType.FindAsync(id);
            _context.PaymentBankingType.Remove(paymentBankingType);
            await _context.SaveChangesAsync();

            return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAll", _context.PaymentBankingType.ToList()) });
        }

        // POST: SuperAdmin/PaymentBankingTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var paymentBankingType = await _context.PaymentBankingType.FindAsync(id);
            _context.PaymentBankingType.Remove(paymentBankingType);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PaymentBankingTypeExists(Guid id)
        {
            return _context.PaymentBankingType.Any(e => e.Id == id);
        }
    }
}

BahokBdDelivery/Areas/SuperAdmin/Views/PaymentBankingTypes/AddOrEdit.cshtml
@model BahokBdDelivery.Models.PaymentBankingType
@{
    ViewData["Title"] = "AddOrEdit";
    Layout = null;
}

<div class="row">
    <div class="col-12 col-lg-10 ">
        <div class="card mb-4">
            <div class="card-header">
               Create Type
            </div>
            <div class="card-body">
                <form asp-action="AddOrEdit"asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPost(this);" autocomplete="off">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <input type="hidden" asp-for="Id" />
                        <label asp-for="BankingMethodName" class="control-label"></label>
                        <input asp-for="BankingMethodName" class="form-control" />
                        <span asp-validation-for="BankingMethodName" class="text-danger"></span>
                    </div>
                 
                    <div class="form-group">
                        <input type="submit" value="Submit" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

BahokBdDelivery/Areas/SuperAdmin/Views/PaymentBankingTypes/Index.cshtml
@model IEnumerable<BahokBdDelivery.Models.PaymentBankingType>
@{
    ViewData["Title"] = "Index";
    //int i = 1;
}

<div class="card mb-4">
    <div class="card-header ">
        <h2>Manage Method</h2>
        <a onclick="showInPopup('@Url.Action("AddOrEdit","PaymentBankingTypes",null,Context.Request.Scheme)','New PaymentBankingTypes' )" class="btn  text-black-50"><i class="fas fa-random"></i> New Type</a>
    </div>
    <div id="view-all"  class="card-body">
        @await Html.PartialAsync("_ViewAll", Model)
    </div>
</div>

BahokBdDelivery/Areas/SuperAdmin/Views/PaymentBankingTypes/_ViewAll.cshtml
@model IEnumerable<BahokBdDelivery.Models.PaymentBankingType>


@if (Model != null)
{
    <table class="table table-responsive table-striped">
        <tbody>
            @foreach (var item in Model)
            {
                <tr>

                    <td style="width:1050px;">
                        @Html.DisplayFor(modelItem => item.BankingMethodName)
                    </td>
                    <td> <a onclick="showInPopup('@Url.Action("AddOrEdit","PaymentBankingTypes",new { id=item.Id},Context.Request.Scheme)','Update PaymentBankingTypes' )" class="btn btn-sm btn-info text-white"><i class="fas fa-random"></i></a></td>
                    <td> <a onclick="Delete('@Url.Action("Delete","PaymentBankingTypes",new { id=item.Id},Context.Request.Scheme)','Delete PaymentBankingTypes' )" class="btn btn-sm btn-danger text-white"><i class="fas fa-trash-alt"></i></a></td>
                </tr>
            }
        </tbody>
    </table>
}    