BahokBdDelivery/Models/DeliveryAreaPrice.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BahokBdDelivery.Models
{
    public class DeliveryAreaPrice
    {
        public Guid Id { get; set; }
        public string Area { get; set; }
        public double Price { get; set; }
    }
}

BahokBdDelivery/Models/DeliveryAreaPrices.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BahokBdDelivery.Models
{

    public partial class DeliveryAreaPrices
    {
        public DeliveryAreaPrices()
        {
            MarchentCharge = new HashSet<MarchentCharge>();
            MarchentStore = new HashSet<MarchentStore>();
        }

        public Guid Id { get; set; }
        public string Area { get; set; }
        public decimal BaseChargeAmount { get; set; }
        public decimal IncreaseChargePerKg { get; set; }
        public bool? Status { get; set; }
        public string CreatedBy { get; set; }
        public DateTimeOffset? CreatedDateTime { get; set; }

        public virtual ICollection<MarchentCharge> MarchentCharge { get; set; }
        public virtual ICollection<MarchentStore> MarchentStore { get; set; }
    }
}

BahokBdDelivery/Areas/SuperAdmin/Controllers/DeliveryAreaPricesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BahokBdDelivery.Data;
using BahokBdDelivery.Models;
using static BahokBdDelivery.Helper;

namespace BahokBdDelivery.Areas.SuperAdmin.Controllers
{
    [Area("SuperAdmin")]
    public class DeliveryAreaPricesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DeliveryAreaPricesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: SuperAdmin/DeliveryAreaPrices
        public async Task<IActionResult> Index()
        {
            return View(await _context.DeliveryAreaPrices.ToListAsync());
        }
        [NoDirectAccess]
        public async Task<IActionResult> AddOrEdit(Guid id)
        {
            if (id == Guid.Parse("00000000-0000-0000-0000-000000000000"))
            {
            
                return View(new DeliveryAreaPrices());
            }

            else
            {
                var deliveryAreaModel = await _context.DeliveryAreaPrices.FindAsync(id);
                if (deliveryAreaModel == null)
                {
                    return NotFound();
                }
                
                return View(deliveryAreaModel);
            }

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit(Guid id, DeliveryAreaPrices deliveryarea)
        {
            if (ModelState.IsValid)
            {
                if (id == Guid.Parse("00000000-0000-0000-0000-000000000000"))
                {
                    DeliveryAreaPrices entity = new DeliveryAreaPrices();
                    entity.Id = Guid.NewGuid();
                    entity.Area = deliveryarea.Area;
                    entity.BaseChargeAmount = deliveryarea.BaseChargeAmount;
                    entity.IncreaseChargePerKg = deliveryarea.IncreaseChargePerKg;
                    _context.Add(entity);
                    await _context.SaveChangesAsync();
                }

                else
                {
                    try
                    {
                        _context.Update(deliveryarea);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!DeliveryAreaPricesExists(deliveryarea.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                }
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAllArea", _context.DeliveryAreaPrices.ToList()) });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "AddOrEdit", deliveryarea) });

        }
        // GET: SuperAdmin/DeliveryAreaPrices/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var deliveryAreaPrices = await _context.DeliveryAreaPrices
                .FirstOrDefaultAsync(m => m.Id == id);
            if (deliveryAreaPrices == null)
            {
                return NotFound();
            }

            return View(deliveryAreaPrices);
        }

        // GET: SuperAdmin/DeliveryAreaPrices/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SuperAdmin/DeliveryAreaPrices/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( DeliveryAreaPrices deliveryAreaPrices)
        {
            if (ModelState.IsValid)
            {
                deliveryAreaPrices.Id = Guid.NewGuid();
                _context.Add(deliveryAreaPrices);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(deliveryAreaPrices);
        }

        // GET: SuperAdmin/DeliveryAreaPrices/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var deliveryAreaPrices = await _context.DeliveryAreaPrices.FindAsync(id);
            if (deliveryAreaPrices == null)
            {
                return NotFound();
            }
            return View(deliveryAreaPrices);
        }

        // POST: SuperAdmin/DeliveryAreaPrices/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, DeliveryAreaPrices deliveryAreaPrices)
        {
            if (id != deliveryAreaPrices.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(deliveryAreaPrices);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DeliveryAreaPricesExists(deliveryAreaPrices.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(deliveryAreaPrices);
        }

        // GET: SuperAdmin/DeliveryAreaPrices/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var deliveryAreaPrices = await _context.DeliveryAreaPrices
                .FirstOrDefaultAsync(m => m.Id == id);
            if (deliveryAreaPrices == null)
            {
                return NotFound();
            }

            return View(deliveryAreaPrices);
        }

        // POST: SuperAdmin/DeliveryAreaPrices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var deliveryAreaPrices = await _context.DeliveryAreaPrices.FindAsync(id);
            _context.DeliveryAreaPrices.Remove(deliveryAreaPrices);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DeliveryAreaPricesExists(Guid id)
        {
            return _context.DeliveryAreaPrices.Any(e => e.Id == id);
        }
    }
}

BahokBdDelivery/Areas/SuperAdmin/Views/DeliveryAreaPrices/AddOrEdit.cshtml
@model BahokBdDelivery.Models.DeliveryAreaPrices
@{
    ViewData["Title"] = "AddOrEdit";
    Layout = null;
}

<div class="card mb-4">
    <div class="card-header">
        Create Branch
    </div>
    <div class="card-body">
        <form asp-action="AddOrEdit" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPost(this);" autocomplete="off">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="Id" />
                <label asp-for="Area" class="control-label"></label>
                <input asp-for="Area" class="form-control" />
                <span asp-validation-for="Area" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BaseChargeAmount" class="control-label"></label>
                <input asp-for="BaseChargeAmount" class="form-control" />
                <span asp-validation-for="BaseChargeAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IncreaseChargePerKg" class="control-label"></label>
                <input asp-for="IncreaseChargePerKg" class="form-control" />
                <span asp-validation-for="IncreaseChargePerKg" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

BahokBdDelivery/Areas/SuperAdmin/Views/DeliveryAreaPrices/Index.cshtml
@model IEnumerable<BahokBdDelivery.Models.DeliveryAreaPrices>

@{
    ViewData["Title"] = "Index";
    int i = 1;
}
<div class="card mb-4">
    <div class="card-header ">
        <h2>Manage Branch</h2>
        <a onclick="showInPopup('@Url.Action("AddOrEdit","DeliveryAreaPrices",null,Context.Request.Scheme)','New Area' )" class="btn  text-black-50"><i class="fas fa-random"></i> New Area</a>
    </div>
    <div id="view-all" class="card-body">
        @await Html.PartialAsync("_ViewAllArea", Model)
    </div>
</div>

@*<div class="row">
    <div class="col-12 col-lg-8  col-md-8 ">
        <div class="card mb-4">
            <div class="card-header ">
                <h2 class="">Manage Area & Price</h2>
                <a asp-action="Create" >Create New</a>
            </div>
            <div class="card-body">
                <table class="table table-responsive table-striped">
                    <thead>
                        <tr>
                            <th>Serial No</th>
                            <th>
                                @Html.DisplayNameFor(model => model.Area)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.BaseChargeAmount)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.IncreaseChargePerKg)
                            </th>
                            <th> @Html.DisplayNameFor(model => model.Status)</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>@i</td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Area)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.BaseChargeAmount)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IncreaseChargePerKg)
                            </td>
                            @if (item.Status==true)
                            {
                                <td class="text-success">Enable</td>
                            }
                            else
                            {
                                <td class="text-warning">Disable</td>
                            }
                            <partial name="_ButtonPartial" model="@item.Id" />
                        </tr>
                            i++;
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>*@

BahokBdDelivery/Areas/SuperAdmin/Views/DeliveryAreaPrices/_ViewAllArea.cshtml
@model IEnumerable<BahokBdDelivery.Models.DeliveryAreaPrices>
@if (Model != null)
{
    <table class="table table-responsive table-striped">
        <tbody>
            @foreach (var item in Model)
            {
            <tr>

                <td style="width:1050px;">
                    <span class="font-weight-bold"> @Html.DisplayFor(modelItem => item.Area)<br /></span>
                    <span>Base Charge:</span>@Html.DisplayFor(modelItem => item.BaseChargeAmount)<br />
                    <span>Increase Charge Per/kg:</span> @Html.DisplayFor(modelItem => item.IncreaseChargePerKg)
                </td>

                <td> <a onclick="showInPopup('@Url.Action("AddOrEdit", "DeliveryAreaPrices", new { id = item.Id }, Context.Request.Scheme)','Update Delivery Area Price' )" class="btn btn-sm btn-info text-white"><i class="fas fa-random"></i></a></td>
                <td><a onclick="Delete('@Url.Action("Delete","DeliveryAreaPrices",new { id=item.Id},Context.Request.Scheme)','Delete Delivery Area Price' )" class="btn btn-sm btn-danger text-white"><i class="far fa-trash-alt"></i></a></td>
            </tr>
            }
        </tbody>
    </table>
}